const fs=require("node:fs");
const required=["index.html","master-admin.html","aegispay-logo.svg","styles.css","app.js","client-auth.js","admin-auth.js","supabase-client.js","supabase-service.js","service-worker.js","manifest.webmanifest","README.md","backend/server.js","backend/data.json","database/schema.sql","database/migrations/20260930_signup_private_evidence_and_kyc.sql","database/migrations/20260930_signup_referral_random_fix.sql","database/migrations/20260930_aegispay_global_runtime_switch.sql","supabase/functions/submit-deposit/index.ts","supabase/functions/submit-kyc/index.ts","supabase/functions/admin-queues/index.ts","supabase/functions/admin-review/index.ts","supabase/functions/telegram-withdrawal/index.ts",".github/workflows/pages.yml",".github/workflows/ci.yml",".github/workflows/android-apk.yml","netlify.toml","package.json","scripts/smoke-api.js"];
for(const f of required) if(!fs.existsSync(f)) throw new Error("Missing required file: "+f);
const html=fs.readFileSync("index.html","utf8");
const js=fs.readFileSync("app.js","utf8");
const clientAuth=fs.readFileSync("client-auth.js","utf8");
const service=fs.readFileSync("supabase-service.js","utf8");
const adminHtml=fs.readFileSync("master-admin.html","utf8");
const adminAuth=fs.readFileSync("admin-auth.js","utf8");
const sql=fs.readFileSync("database/schema.sql","utf8");
const securitySql=fs.readFileSync("database/migrations/20260930_signup_private_evidence_and_kyc.sql","utf8");
const runtimeSql=fs.readFileSync("database/migrations/20260930_aegispay_global_runtime_switch.sql","utf8");
const signupFix=fs.readFileSync("database/migrations/20260930_signup_referral_random_fix.sql","utf8");
if(!html.includes('id="app"')) throw new Error("App mount missing");
if(!html.includes('./client-auth.js')||!html.includes('./supabase-client.js')||!html.includes('./supabase-service.js')) throw new Error("Client Auth entry is incomplete");
if(html.includes('./aegis-core.js')||html.includes('./app.js')) throw new Error("Client entry must not load local demo authentication or data");
for(const marker of ["claim_aegispay_profile","signUp","signInWithPassword","resetPasswordForEmail","set_my_language","request_withdrawal","app_runtime_enabled","set_app_runtime_enabled"]) if(!service.includes(marker)) throw new Error("Supabase Auth integration missing: "+marker);
for(const marker of ["signupForm","depositForm","kycForm","aegispay-language","submit-deposit","submit-kyc"]) if(!clientAuth.includes(marker)) throw new Error("Client operations UI marker missing: "+marker);
if(adminHtml.includes("./app.js")||adminHtml.includes("./aegis-core.js")||!adminHtml.includes("./admin-auth.js")) throw new Error("Master Admin must use protected Supabase Auth, not local demo state");
for(const marker of ["admin-queues","admin-review","MASTER ADMIN","setAppRuntimeEnabled","aria-checked","Resume app"]) if(!adminAuth.includes(marker)) throw new Error("Master Admin workflow missing: "+marker);
for(const marker of ["app_runtime_enabled","set_app_runtime_enabled","guard_app_runtime_mutations","verification_upload_own"]) if(!runtimeSql.includes(marker)) throw new Error("Global runtime switch migration missing: "+marker);
if(signupFix.includes("gen_random_bytes")||!signupFix.includes("gen_random_uuid")) throw new Error("Signup referral code must not depend on the unavailable pgcrypto random-bytes function");
if(!clientAuth.includes("retry-runtime")||!clientAuth.includes("tg-spinner")) throw new Error("Client auth feedback or pause screen is missing");
for(const marker of ["kyc_verifications","private-verification","request_withdrawal","require_deposit_evidence_review","role = 'USER'"]) if(!securitySql.includes(marker)) throw new Error("Operational security migration missing: "+marker);
if(!fs.readFileSync("database/migrations/20260930_withdrawal_role_and_payout_recovery.sql","utf8").includes("fail_unbroadcast_withdrawal")) throw new Error("Unbroadcast payout recovery migration missing");
if(fs.readFileSync("service-worker.js","utf8").includes("url.origin!==self.location.origin")){}else throw new Error("Service worker must not cache cross-origin/authenticated responses");
for(const file of ["aegis-core.js","client-auth.js","master-admin.html","README.md"]) if(/aegispay\.demo|APMASTER|APADMIN|AP10023/.test(fs.readFileSync(file,"utf8"))) throw new Error("Legacy demo login identity remains in "+file);
for(const marker of ["Welcome Back","Deposit","AegisPay Shop","Proceed to Complete Tasks","Referrals","My Profile","AI Assistant","Withdraw","Notifications","MASTER ADMIN"]) if(!js.includes(marker)) throw new Error("Required UI marker missing: "+marker);
for(const endpoint of ["/api/v1/health","/api/v1/liquidity/metrics","/api/v1/liquidity/audit","/api/v1/ai-assistant/recommendation","/api/v1/ai-assistant/chat","/api/v1/withdraw/request","/api/v1/withdraw/requests","/api/v1/admin/approve"]) if(!fs.readFileSync("backend/server.js","utf8").includes(endpoint)) throw new Error("Required API missing: "+endpoint);
if(!sql.includes("CREATE EXTENSION IF NOT EXISTS pgcrypto")) throw new Error("pgcrypto extension missing");
console.log("AegisPay repository validation: PASS");
