const fs=require("node:fs");
const required=["index.html","master-admin.html","aegispay-logo.svg","styles.css","client-auth.js","admin-auth.js","supabase-client.js","supabase-service.js","aegis-auth-redirect.js","_redirects","service-worker.js","manifest.webmanifest","README.md","backend/server.js","backend/data.json","database/schema.sql","database/migrations/20260930_signup_private_evidence_and_kyc.sql","database/migrations/20260930_signup_referral_random_fix.sql","database/migrations/20260930_aegispay_global_runtime_switch.sql","database/migrations/20260930_dual_withdrawal_approval_dashboard_metrics.sql","database/migrations/20260930_telegram_withdrawal_txid_guard.sql","database/migrations/20260930_admin_rpc_role_null_guards.sql","database/migrations/20260930_clear_unverified_testnet_wallet.sql","database/migrations/20260930_network_aware_deposit_credit.sql","database/migrations/20260930_rls_and_foreign_key_indexes.sql","database/migrations/20260930_withdrawal_role_and_payout_recovery.sql","supabase/functions/submit-deposit/index.ts","supabase/functions/submit-kyc/index.ts","supabase/functions/admin-queues/index.ts","supabase/functions/admin-review/index.ts","supabase/functions/telegram-withdrawal/index.ts","supabase/functions/verify-deposit/index.ts","supabase/functions/monitor-deposits/index.ts",".github/workflows/pages.yml",".github/workflows/ci.yml",".github/workflows/android-apk.yml",".github/workflows/android-apk-export.yml","netlify.toml","package.json","scripts/smoke-api.js"];
for(const f of required) if(!fs.existsSync(f)) throw new Error("Missing required file: "+f);
const html=fs.readFileSync("index.html","utf8");
const clientJs=fs.readFileSync("client-auth.js","utf8");
const adminJs=fs.readFileSync("admin-auth.js","utf8");
const redirectJs=fs.readFileSync("aegis-auth-redirect.js","utf8");
const clientAuth=fs.readFileSync("client-auth.js","utf8");
const service=fs.readFileSync("supabase-service.js","utf8");
const adminHtml=fs.readFileSync("master-admin.html","utf8");
const adminAuth=fs.readFileSync("admin-auth.js","utf8");
const sql=fs.readFileSync("database/schema.sql","utf8");
const securitySql=fs.readFileSync("database/migrations/20260930_signup_private_evidence_and_kyc.sql","utf8");
const runtimeSql=fs.readFileSync("database/migrations/20260930_aegispay_global_runtime_switch.sql","utf8");
const signupFix=fs.readFileSync("database/migrations/20260930_signup_referral_random_fix.sql","utf8");
if(!html.includes('id="app"')) throw new Error("App mount missing");
if(!html.includes('./client-auth.js')||!html.includes('./supabase-client.js')||!html.includes('./supabase-service.js')) throw new Error("Client Auth entry is incomplete");
if(html.includes('./aegis-core.js')||html.includes('./app.js')) throw new Error("Client entry must not load local demo authentication or data");
for(const marker of ["claim_aegispay_profile","signUp","signInWithPassword","resetPasswordForEmail","set_my_language","request_withdrawal","app_runtime_enabled","set_app_runtime_enabled"]) if(!service.includes(marker)) throw new Error("Supabase Auth integration missing: "+marker);
for(const marker of ["signupForm","depositForm","kycForm","aegispay-language","submit-deposit","submit-kyc"]) if(!clientAuth.includes(marker)) throw new Error("Client operations UI marker missing: "+marker);
if(adminHtml.includes("./app.js")||adminHtml.includes("./aegis-core.js")||!adminHtml.includes("./admin-auth.js")) throw new Error("Master Admin must use protected Supabase Auth, not local demo state");
for(const marker of ["admin-queues","admin-review","MASTER ADMIN","setAppRuntimeEnabled","aria-checked","Resume app","confirmedDepositsUsdt","completedWithdrawalsCount","telegram-check","telegram-resend"]) if(!adminAuth.includes(marker)) throw new Error("Master Admin workflow missing: "+marker);
for(const marker of ["app_runtime_enabled","set_app_runtime_enabled","guard_app_runtime_mutations","verification_upload_own"]) if(!runtimeSql.includes(marker)) throw new Error("Global runtime switch migration missing: "+marker);
if(signupFix.includes("gen_random_bytes")||!signupFix.includes("gen_random_uuid")) throw new Error("Signup referral code must not depend on the unavailable pgcrypto random-bytes function");
if(!clientAuth.includes("retry-runtime")||!clientAuth.includes("tg-spinner")) throw new Error("Client auth feedback or pause screen is missing");
for(const marker of ["kyc_verifications","private-verification","request_withdrawal","require_deposit_evidence_review","role = 'USER'"]) if(!securitySql.includes(marker)) throw new Error("Operational security migration missing: "+marker);
if(!fs.readFileSync("database/migrations/20260930_withdrawal_role_and_payout_recovery.sql","utf8").includes("fail_unbroadcast_withdrawal")) throw new Error("Unbroadcast payout recovery migration missing");
const dual=fs.readFileSync("database/migrations/20260930_dual_withdrawal_approval_dashboard_metrics.sql","utf8");
for(const marker of ["record_withdrawal_telegram_decision","panel_decision","telegram_decision","status='PAID'","aegispay_admin_dashboard_totals"]) if(!dual.includes(marker)) throw new Error("Dual approval or confirmed totals migration missing: "+marker);
if(!fs.readFileSync("database/migrations/20260930_telegram_withdrawal_txid_guard.sql","utf8").includes("A transaction ID exists")) throw new Error("Telegram decision must stop for payout reconciliation");
const roleGuard=fs.readFileSync("database/migrations/20260930_admin_rpc_role_null_guards.sql","utf8");
if(!roleGuard.includes("COALESCE(public.current_app_role(),'') <> 'MASTER ADMIN'")) throw new Error("Sensitive admin RPCs must reject missing Master Admin profiles");
for(const marker of ["finalize_withdrawal","master_admin_adjust_balance","set_user_account_status","FROM PUBLIC,anon,service_role"]) if(!roleGuard.includes(marker)) throw new Error("Admin RPC authorization hardening is incomplete: "+marker);
const payout=fs.readFileSync("supabase/functions/execute-payout/index.ts","utf8");
for(const marker of ["TRON_TESTNET_PAYOUT_PRIVATE_KEY","SHASTA_USDT","panel_decision","telegram_decision","api.shasta.trongrid.io"]) if(!payout.includes(marker)) throw new Error("Guarded testnet payout integration missing: "+marker);
if(!fs.readFileSync("service-worker.js","utf8").includes("url.origin!==self.location.origin")) throw new Error("Service worker must not cache cross-origin/authenticated responses");
for(const file of ["client-auth.js","admin-auth.js","master-admin.html","README.md"]) if(/aegispay\.demo|APMASTER|APADMIN|AP10023/.test(fs.readFileSync(file,"utf8"))) throw new Error("Legacy demo login identity remains in "+file);
for(const marker of ["signupForm","depositForm","kycForm","submit-deposit","submit-kyc","aegispay-language"]) if(!clientJs.includes(marker)) throw new Error("Client workflow marker missing: "+marker);
for(const marker of ["admin-queues","admin-review","MASTER ADMIN","setAppRuntimeEnabled","confirmedDepositsUsdt","completedWithdrawalsCount","telegram-check","telegram-resend"]) if(!adminJs.includes(marker)) throw new Error("Admin workflow marker missing: "+marker);
for(const marker of ["exchangeCodeForSession","setSession","AegisAuthRedirect"]) if(!redirectJs.includes(marker)) throw new Error("Auth callback handler missing: "+marker);
for(const endpoint of ["/api/v1/health","/api/v1/liquidity/metrics","/api/v1/liquidity/audit","/api/v1/ai-assistant/recommendation","/api/v1/ai-assistant/chat","/api/v1/withdraw/request","/api/v1/withdraw/requests","/api/v1/admin/approve"]) if(!fs.readFileSync("backend/server.js","utf8").includes(endpoint)) throw new Error("Required API missing: "+endpoint);
if(!sql.includes("CREATE EXTENSION IF NOT EXISTS pgcrypto")) throw new Error("pgcrypto extension missing");
const authManifest=fs.readFileSync("android/app/src/main/AndroidManifest.xml","utf8");
const authGradle=fs.readFileSync("android/app/build.gradle","utf8");
if(!authManifest.includes('android:scheme="@string/auth_scheme"')) throw new Error("Android auth scheme binding missing");
for(const marker of ["auth_scheme","com.aegispay.app.client","com.aegispay.app.admin","assembleClientDebug","assembleAdminDebug"]) if(!(authGradle.includes(marker)||fs.readFileSync(".github/workflows/android-apk.yml","utf8").includes(marker))) throw new Error("Android portal flavor configuration missing: "+marker);
const redirectService=fs.readFileSync("supabase-service.js","utf8");
for(const marker of ["https://aegispay-pro.netlify.app/auth/callback","com.aegispay.app.client://auth/callback","emailRedirectTo","redirectTo"]) if(!redirectService.includes(marker)) throw new Error("Production auth redirect configuration missing: "+marker);
console.log("AegisPay repository validation: PASS");

